version: '3.7'
services:
  base: &base
    build:
      context: .
      target: base
    environment:
      - "DISPLAY=unix$DISPLAY"
    volumes:
      # - .:/home/wineuser
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
       - /dev/snd:/dev/snd
  app:
    <<: *base
    build: .
